version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: fenatan/node_app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node /usr/src/app/index.js
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - nodenet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: fenatan/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports: 
      - "8080:80"
  
networks:
  nodenet:
    driver: bridge
